### PR TITLE
Fix error builder to be (ever) called; Remove deprecated loading child

### LINKED ISSUE #337: [BUG] errorBuilder is never called
**Describe the bug**
Docs say to use errorBuilder instead of `loadFailedChild`, but errorBuilder is never called. In the source code, it's defined, but is never passed into ImageWrapper.

**To Reproduce**
Implement errorBuilder

**What is the current behavior?**
errorBuilder is not called

**Expected behavior**
errorBuilder should be called on failures

**Screenshots**

**Is this a *feature* or report a *bug*?**

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. The output of flutter doctor can help too. **

**What is the expected behavior?**

**Which versions of Flutter/Photo View, and which browser / OS are affected by this issue? Did this work in previous versions of Photo View?**

**Additional context**

### PR DESCRIPTION
**Pull request by renancaraujo**
This PR fixes some issues regarding error builder.
- fix #337. 
- Remove deprecated `loadingChild`
- Makes `backgroundDecoration` to be the background of the default error icon.

### CODE REVIEW

File: example/lib/screens/examples/network-images.dart [hunk 1]
```diff
@@ -50,11 +50,37 @@ class NetworkExamples extends StatelessWidget {
...
+                      "https://pudim.com.br/sss.jpg",
+                    ),
+                    errorBuilder: (_, __, ___) {
+                      return Container(
+                          child: Column(
+                        children: [
+                          Image.asset("assets/neat.gif"),
+                          const Text("well, that went badly"),
+                        ],
+                      ));
```
Comment (luanpotter) [inline example/lib/screens/examples/network-images.dart:77]: missing trailing comma
